apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  selector:
    matchLabels:
      app: webapplication
      tier: backend
  template:
    metadata:
      labels:
        app: webapplication
        tier: backend
    spec:
      containers:
        - name: backend
          image: kubernetes-learning/backend:latest
          imagePullPolicy: Never

          readinessProbe:
            httpGet:
              path: /api/health
              port: 8080
            failureThreshold: 7
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /api/health
              port: 8080
            failureThreshold: 7
            periodSeconds: 10

          ports:
          - containerPort: 8080

          resources:
            limits:
              cpu: 400m
              memory: 800Mi
            requests:
              cpu: 20m
              memory: 200Mi