apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webapplication
      tier: backend
  template:
    metadata:
      labels:
        app: webapplication
        tier: backend
    spec:
      containers:
        - name: backend
          image: kubernetes-learning/backend:latest
          imagePullPolicy: Never

          readinessProbe:
            httpGet:
              path: /api/health
              port: 8080
            failureThreshold: 4
            periodSeconds: 5

          livenessProbe:
            httpGet:
              path: /api/health
              port: 8080
            failureThreshold: 4
            periodSeconds: 5

          ports:
          - containerPort: 8080