apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapplication
      tier: backend
  template:
    metadata:
      labels:
        app: webapplication
        tier: backend
    spec:
      containers:
        - name: backend
          image: kubernetes-learning/backend:latest
          imagePullPolicy: Never
          ports:
          - containerPort: 8080