apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: app
spec:
  selector:
    app: webapplication
    tier: backend
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
