apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    app: webapplication
    tier: frontend
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
