apiVersion: v1
kind: Service
metadata:
  name: webapplication-service
spec:
  selector:
    app: webapplication
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30000
      protocol: TCP
