apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: backend
  namespace: app
spec:
  minReplicas: 1
  maxReplicas: 10
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: backend
  behavior:
    scaleUp:
      policies:
      - type: Pods
        value: 1
        periodSeconds: 1
    scaleDown:
      stabilizationWindowSeconds: 0
      selectPolicy: Min
      policies:
      - type: Pods
        value: 1
        periodSeconds: 1
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
